# Generated by Django 3.2.18 on 2023-11-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Дилер',
                'verbose_name_plural': 'Дилеры',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=256, verbose_name='Уникальный номер позиции')),
                ('price', models.CharField(max_length=256, verbose_name='Цена')),
                ('product_url', models.SlugField(max_length=2560, verbose_name='Адрес страницы, откуда собранны данные')),
                ('product_name', models.CharField(max_length=256, verbose_name='Заголовок продаваемого товара')),
                ('date', models.DateTimeField(max_length=256, verbose_name='Дата получения информации')),
                ('dealer_id', models.CharField(max_length=256, verbose_name='Идентефикатор дилера')),
            ],
            options={
                'verbose_name': 'Цена дилера',
                'verbose_name_plural': 'Цены дилеров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(max_length=256, verbose_name='ID товара')),
                ('article', models.CharField(max_length=256, verbose_name='Артикул товара')),
                ('ean_13', models.CharField(max_length=13, verbose_name='Код товара')),
                ('name', models.CharField(max_length=256, verbose_name='Название товара')),
                ('cost', models.CharField(max_length=256, verbose_name='Стоимость')),
                ('recommended_price', models.CharField(max_length=256, verbose_name='Рекомендованная цена')),
                ('category_id', models.CharField(max_length=256, verbose_name='Категория товара')),
                ('ozon_name', models.CharField(max_length=256, verbose_name='Название товара на Озоне')),
                ('name_1c', models.CharField(max_length=256, verbose_name='Название товара в 1С')),
                ('wb_name', models.CharField(max_length=256, verbose_name='Название товара на Вайлдберриз')),
                ('ozon_article', models.CharField(max_length=256, verbose_name='Артикул для Озон')),
                ('wb_article', models.CharField(max_length=256, verbose_name='Артикул для Вайлберриз')),
                ('ym_article', models.CharField(max_length=256, verbose_name='артикул для Яндекс.Маркета')),
                ('wb_article_td', models.CharField(max_length=256, verbose_name='Артикул_ВБ_тд')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product', verbose_name='Продукт')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.price', verbose_name='Цена')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='products.dealer', verbose_name='Дилер')),
            ],
            options={
                'verbose_name': 'Товар дилера',
                'verbose_name_plural': 'Товары дилера',
            },
        ),
        migrations.AddConstraint(
            model_name='dealer',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_dealer_name'),
        ),
    ]
