version: '3.3'

volumes:
  pg_data:

services:

  db:
    container_name: matching-db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: matching-redis
    image: redis:7.0.5-alpine
    hostname: redis

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/app/build
    depends_on:
      - backend

  backend:
    container_name: matching-backend
    depends_on:
      - db
      - redis
    restart: always
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
