version: '3.3'

volumes:
  pg_data:
  static:

services:

  db:
    container_name: matching-db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    hostname: redis

  flower:
    container_name: flower
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - "5557:5555"
    depends_on:
      - redis

  frontend:
    container_name: matching-frontend
    image: primestr/matching_frontend
    command: cp -r /app/build/. /app/static/.
    volumes:
      - static:/app/static/

    depends_on:
      - backend

  backend:
    container_name: matching-backend
    depends_on:
      - db
      - redis
    restart: always
    image: primestr/matching_backend
    env_file: .env
    volumes:
      - static:/app/static/

  nginx:
    container_name: matching-nginx
    depends_on:
      - frontend
    image: primestr/matching_nginx
    restart: always
    volumes:
      - static:/app/static/
    ports:
      - "8500:80"
